---
- name: Update Packages and deps
  block:
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        cache_valid_time: 3600
        update_cache: true
      register: _pre_update_apt_cache
      until: _pre_update_apt_cache is succeeded
      when:
        - ansible_pkg_mgr == "apt"

    - name: Install dependencies
      become: true
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      register: _install_dep_packages
      until: _install_dep_packages is succeeded
      retries: 5
      delay: 2
      with_items: "{{ distribution__dependencies }}"

- name: Install distribution block
  when: (not ansible_check_mode and (distribution__active_version.stdout != distribution__version_target))
  block:
    - name: Download distribution archive
      ansible.builtin.get_url:
        url: "{{ distribution__dl_url }}/{{ distribution__filename }}.tar.gz"
        dest: "/tmp/{{ distribution__filename }}.tar.gz"
        checksum: "sha256:{{ distribution__dl_url }}/{{ distribution__filename }}.tar.gz.sha256"
        mode: 0640
      register: _download_archive
      become: false
      until: _download_archive is succeeded
      retries: 5
      delay: 2

    - name: Unpack distribution binary
      ansible.builtin.command:
        cmd: "xz -k -d /tmp/{{ gitea_filename }}.xz"
        creates: "/tmp/{{ gitea_filename }}"

    - name: Propagate distribution binary
      become: true
      ansible.builtin.copy:
        src: "/tmp/{{ gitea_filename }}"
        remote_src: true
        dest: "{{ gitea_full_executable_path }}"
        mode: 0755
        owner: root
        group: root
      notify: "Restart gitea"
