---
- name: Run optional versionscheck
  ansible.builtin.include_tasks:
    file: 'versioncheck.yml'
  when: submodules_versioncheck | bool

- name: Get distribution latest version
  ansible.builtin.include_tasks:
    file: 'set_distribution_version.yml'
