---
- name: "Create distribution Group"
  become: true
  ansible.builtin.group:
    name: "{{ distribution__group }}"
    system: true
    state: "present"
  notify: 'systemctl restart registry'

- name: "Create distribution user"
  become: true
  ansible.builtin.user:
    name: "{{ distribution__user }}"
    comment: "distribution user for registry"
    group: "{{ distribution__group }}"
    groups: "{{ distribution__groups | default(omit) }}"
    home: "{{ distribution__home }}"
    shell: "/usr/sbin/nologin"
    system: true
  notify: 'systemctl restart registry'
